network:
  version: 2
  ethernets:
    eth0:
      addresses:
      - 192.168.2.111/24
  
  wifis:
    wlan0:
      addresses: []
      dhcp4: true
      access-points:
        502HWa-4057C4:
          password: 1500966b

  version: 2
